### ISSUE TITLE
Switch from using gh-pages manually to CI/CD

### ISSUE THREAD

**Issue by jackharrhy** [millerm30/chore-bucks#5]
Steal stuff from Evan :) https://github.com/evnwttn/ao/blob/main/.github/workflows/gh-pages.yml

instead of:

```yml
      - name: Install dependencies
        run: cd my-app && npm install

      - name: Build
        run: cd my-app && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: my-app/build
```

you would have:

```yml
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
```
